version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls
      - aws s3 sync ./build/ s3://ci-cd-test-host/ --delete --acl public-read
artifacts:
  files:
    - build/**/*