export const adminUserConstants = {
    LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    LOGIN_FAILEURE: 'ADMIN_LOGIN_FAILURE',

    LOGOUT: 'ADMIN_LOGOUT',

    GET_ADMIN_REQUEST: 'GET_ADMIN_REQUEST',
    GET_ADMIN_SUCCESS: 'GET_ADMIN_SUCCESS',
    GET_ADMIN_FAILURE: 'GET_ADMIN_FAILURE',
}