const organizationConstants = {
  GET_ALL_REQUEST : 'GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE',

  CREATE_ORGANIZATION_REQUEST: 'CREATE_ORGANIZATION_REQUEST',
  CREATE_ORGANIZATION_SUCCESS: 'CREATE_ORGANIZATION_SUCCESS',
  CREATE_ORGANIZATION_FAILURE: 'CREATE_ORGANIZATION_FAILURE',
};

export default organizationConstants;
