const organizationDetailsConstants = {
  ORGANIZATION_DETAILS_REQUEST : 'ORGANIZATION_DETAILS_REQUEST',
  ORGANIZATION_DETAILS_SUCCESS : 'ORGANIZATION_DETAILS_SUCCESS',
  ORGANIZATION_DETAILS_FAILURE : 'ORGANIZATION_DETAILS_FAILURE',
};

export default organizationDetailsConstants;
