const userConstants = {
  GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',

  USER_EDIT_MODE_TOGGLE: 'USER_EDIT_MODE_TOGGLE',

  GET_USER_BY_ID_EDIT_MODE_REQUEST: 'GET_USER_BY_ID_EDIT_MODE_REQUEST',
  GET_USER_BY_ID_EDIT_MODE_SUCCESS: 'GET_USER_BY_ID_EDIT_MODE_SUCCESS',
  GET_USER_BY_ID_EDIT_MODE_FAILURE: 'GET_USER_BY_ID_EDIT_MODE_FAILURE',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  BLOCK_USER_REQUEST: 'BLOCK_USER_REQUEST',
  BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
  BLOCK_USER_FAILURE: 'BLOCK_USER_FAILURE',

  UNBLOCK_USER_REQUEST: 'UNBLOCK_USER_REQUEST',
  UNBLOCK_USER_SUCCESS: 'UNBLOCK_USER_SUCCESS',
  UNBLOCK_USER_FAILURE: 'UNBLOCK_USER_FAILURE',

  TOGGLE_CONFIRMATION_MODAL: 'TOGGLE_CONFIRMATION_MODAL',
};

export default userConstants;
