const userConstants = {
  GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',

  USER_EDIT_MODE_TOGGLE: 'USER_EDIT_MODE_TOGGLE',

  GET_USER_BY_ID_EDIT_MODE_REQUEST: 'GET_USER_BY_ID_EDIT_MODE_REQUEST',
  GET_USER_BY_ID_EDIT_MODE_SUCCESS: 'GET_USER_BY_ID_EDIT_MODE_SUCCESS',
  GET_USER_BY_ID_EDIT_MODE_FAILURE: 'GET_USER_BY_ID_EDIT_MODE_FAILURE',

  TOGGLE_CONFIRMATION_MODAL: 'TOGGLE_CONFIRMATION_MODAL',
};

export default userConstants;
