version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - build/**/*
    - aws s3 sync . s3://ci-cd-test-host